name: 🚀 New KG
description: Submission form for a new Knowledge Graph.
title: "[New KG] kg-title"
labels: ["new-kg"]
body:

- type: input
  attributes:
    label: KG ID
    description: Set unique ID of your KG. (e.g. food-kg).  Check for already used IDs at https://databus.dbpedia.org/knowledge-graph-catalog
  validations:
    required: true

- type: input
  attributes:
    label: KG Title 
    description: Set the title of the KG.
  validations:
    required: true

- type: textarea
  attributes:
    label: KG Short Abstract
    description: Provide short description of the KG (e.g. 2 sentences). Maximum 300 chars.
  validations:
    required: true

- type: textarea
  attributes:
    label: KG Full Description
    description: Provide extended description of the KG. You can either use free text or markdown syntax.
  validations:
    required: true

- type: input
  attributes:
    label: License
    description: Provide the general license for the KG, e.g. http://purl.oclc.org/NET/rdflicense/cc-by3.0 Provide the license as URL.
  validations:
    required: true

- type: input
  attributes:
    label: KG Homepage 
    description: Home page for the KG.
  validations:
    required: true

- type: dropdown
  id: domain
  attributes:
    label: KG Primary Domain
    description: Select the primary domain of the Knowledge Graph.
    options:
      - Cross-domain
      - Geography & Environment
      - Government & Public Sector
      - Life Sciences & Health
      - Economy, Industry & Infrastructure
      - Publications, Education & Research
      - Media, Culture & Entertainment
      - Linguistics, Social & Digital Knowledge Systems
  validations:
    required: true

- type: input
  id: keywords
  attributes:
    label: Keywords
    description: Provide 3–8 comma-separated keywords whiich describe the KG.
    placeholder: linked data, rdf, geography
  validations:
    required: true

- type: input
  id: sparql-name
  attributes:
    label: SPARQL Endpoint URL
    description: Provide URL to the SPARQL endpoint, if it exist. (optional)
  validations:
    required: false

- type: input
  id: maintainer-name
  attributes:
    label: KG Maintainer Name
    description: Primary contact person. (optional)
  validations:
    required: false

- type: input
  id: maintainer-contact
  attributes:
    label: KG Maintainer Contact
    description: Email address. (optional)
    placeholder: your@email.com
  validations:
    required: false

- type: input
  id: maintainer-github
  attributes:
    label: KG Maintainer GitHub Username
    description:  Optional.
  validations:
    required: false
    
- type: textarea
  id: artifacts
  attributes:
    label: KG Content (Artifacts, Versions and Distributions)
    description: |
      Describe the content of your Knowledge Graph using YAML.

      The structure follows this hierarchy:
      
      ```
      Knowledge Graph
        └── Artifact(s)
              └── Version(s)
                    └── Distribution file(s)
      ```
      
      - An **artifact** represents a logical part of the Knowledge Graph.
      Typically, an artifact corresponds to a partition of the KG (e.g., a specific dataset, module, language version, or data subset).

      - A **version** represents a specific release of an artifact at a particular point in time.

      - A **distribution** represents a single downloadable file belonging to a specific artifact version.
      Each distribution should provide the file URL and its format (and compression, if applicable).

      Update the example below with information about your Knowledge Graph.
    render: yaml
    value: |
      - artifact: first-artifact
        title: First Artifact
        abstract: Short description.
        description: Longer description.

        versions:
          - version: 2026.07.10
            title: First Artifact
            abstract: Short description.
            description: Longer description.
            license: http://purl.oclc.org/NET/rdflicense/cc-by3.0

            distributions:
              - file: https://example.org/file1.ttl.bz2
                format: ttl
                compression: bz2

      - artifact: second-artifact
        title: Second Artifact
        abstract: Short description.
        description: Longer description.

        versions:
          - version: 2026.07.10
            title: Second Artifact
            abstract: Short description.
            description: Longer description.
            license: http://purl.oclc.org/NET/rdflicense/cc-by3.0

            distributions:
              - file: https://example.org/file2.ttl.bz2
                format: ttl
                compression: bz2
  validations:
    required: true
