name: 🚀 New KG
description: Submission form for a new Knowledge Graph.
title: "[New KG] <kg-title>"
labels: ["new-kg"]
body:

- type: input
  attributes:
    label: KG ID
    description: Set unique ID of your KG. (e.g. food-kg).  Check for already used ids at https://databus.dbpedia.org/knowledge-graph-catalog
  validations:
    required: true

- type: input
  attributes:
    label: KG Title 
    description: Set the title of the KG.
  validations:
    required: true

- type: textarea
  attributes:
    label: abstract
    description: Provide short description of the KG (e.g. 2 sentences). Maximum 300 chars.
  validations:
    required: true

- type: textarea
  attributes:
    label: description
    description: Provide extended description of the KG. You can either use free text or markdown syntax.
  validations:
    required: true

- type: input
  attributes:
    label: license 
    description: Provide the general license for the KG, e.g. http://purl.oclc.org/NET/rdflicense/cc-by3.0
  validations:
    required: true

- type: input
  attributes:
    label: homepage 
    description: Home page for the KG, if exist.
  validations:
    required: true

- type: dropdown
  id: domain
  attributes:
    label: Primary Domain
    description: Select the primary domain of the Knowledge Graph.
    options:
      - Cross-domain
      - Geography & Environment
      - Government & Public Sector
      - Life Sciences & Health
      - Economy, Industry & Infrastructure
      - Publications, Education & Research
      - Media, Culture & Entertainment
      - Linguistics, Social & Digital Knowledge Systems
  validations:
    required: true

- type: input
  id: keywords
  attributes:
    label: Keywords
    description: Provide 3–8 comma-separated keywords.
    placeholder: linked data, rdf, geography
  validations:
    required: true

- type: input
  id: sparql-name
  attributes:
    label: SPARQL Endpoint
    description: Provide URL to the SPARQL endpoint, if it exist. (optional)
  validations:
    required: false

    
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.
  validations:
    required: false
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: false
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. In this environment...
      1. With this config...
      1. Run '...'
      1. See error...
  validations:
    required: false
- type: textarea
  attributes:
    label: Environment
    description: |
      examples:
        - **OS**: Ubuntu 20.04
        - **Node**: 13.14.0
        - **npm**: 7.6.3
    value: |
        - OS:
        - Node:
        - npm:
    render: markdown
  validations:
    required: false
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
