name: Check Dataset URLs

on:
  push:
    paths:
      - "kgs/*.yaml"
  pull_request:
    paths:
      - "kgs/*.yaml"
  schedule:
    - cron: '0 0 * * *'  # daily at midnight UTC

jobs:
  check-urls:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Install dependencies
      - name: Install dependencies
        run: pip install pyyaml requests

      # Run URL check script for all YAMLs
      - name: Run URL check and update YAML
        run: |
          for f in kgs/*.yaml; do
            python scripts/check_url_update_yaml.py "$f"
          done

      # Commit changes if any
      - name: Commit updated YAML
        run: |
          git config user.name "LOD Cloud Bot"
          git config user.email "bot@lod-cloud.org"
          git add kgs/*.yaml
          git diff-index --quiet HEAD || git commit -m "Update dataset status & last_verified"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
