name: GitHub Pages Hourly Build

on:
  schedule:
    - cron: '0 * * * *'  # every hour at minute 0
  workflow_dispatch:      # allows manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./          # root folder with index.html
          destination_branch: gh-pages
