name: Publish Knowledge Graphs to Databus

on:
  push:
    paths:
      - "knowledge-graphs/**/*.yaml"
  pull_request:
    paths:
      - "knowledge-graphs/**/*.yaml"

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      DATABUS_API_KEY: ${{ secrets.DATABUS_API_KEY }}

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2️⃣ Set up Python
      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3️⃣ Install dependencies
      - name: Install Python dependencies
        run: pip install --upgrade pip && pip install pyyaml requests

      # 4️⃣ Validate YAML and check URLs
      - name: Validate YAML & check dataset URLs
        id: validate
        run: |
          python scripts/check_url_update_yaml.py knowledge-graphs/**/*.yaml

      # 5️⃣ Publish to Databus via HTTP **only if validation passed**
      - name: Publish to Databus
        if: ${{ success() }}        # <-- this ensures this step runs only if previous step succeeded
        run: python scripts/publish_to_databus_http.py knowledge-graphs/**/*.yaml

      # 6️⃣ Commit updated YAML back to the repository
      - name: Commit YAML updates
        if: ${{ success() }}        # <-- commit only if validation and publish succeeded
        run: |
          git config user.name "LOD Cloud Bot"
          git config user.email "bot@lod-cloud.org"
          git add knowledge-graphs/**/*.yaml
          git diff-index --quiet HEAD || git commit -m "Update Databus metadata"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
